# port
server:
  port: 8080

# spring
spring:
  application:
    name: gateway

  config:
    import:
      optional:nacos://8.153.102.70:8848

  cloud:
    nacos:
      discovery:
        server-addr: 8.153.102.70:8848
      config:
        server-addr: 8.153.102.70:8848
